version: "3"

services:
  #
  # This section shows the services that would run on-prem
  #
  redash:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - redash
    restart: always

  #
  # I have not experimented with this, but if your cloud instance uses Redis
  # too, you might connect to the cloud Redis instead, so you can mix on-prem
  # and cloud Redash. If you want to be safe (and that is probably better) just
  # run Redis on-prem and a separate one on the cloud.
  #
  redis:
    image: redis:5.0-alpine
    restart: always


  #
  # If all you are doing is experimenting, this gives you a clean Postgres
  # instance to play with. For normal operations, you would omit this section
  # and update the `.env` file to point to the cloud Postgres instance.
  #
  postgres:
    image: postgres:9.6-alpine
    env_file: .env
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    restart: always

